### ISSUE TITLE
Module microphone: (on raspbian bulleyes, python 3.9)  TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by mdaadoun** [42Angouleme/robot-python#29]
python3 main.py

**Comment by Zecat** [comment]
Probablement dù à une utlisation de code d'une version de python > 3.9. Si c'est ça, soit on se décide à se limiter aux fonctionnalité python 3.9, ou on met à jour python sur la machine. Je crois qu'on peut utiliser `pipenv` pour lancer un environnement virtuel dans une version specifique de python.
